server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/projects/**

        - id: sprint-service
          uri: lb://SPRINT-SERVICE
          predicates:
            - Path=/api/v1/sprints/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: stories-service
          uri: lb://STORIES-SERVICE
          predicates:
            - Path=/api/v1/stories/**

        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/api/v1/activity/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation2026